future
requests
retrying
python-dateutil
pytz
pyyaml>=5.1
